### ISSUE TITLE
DDS support Ubuntu20.04

### ISSUE THREAD

**Issue by AllenDun** [IDEA-Research/deepdataspace#154]
DDS now only support Ubuntu18.04? I just install the DDS in Ubuntu20.04, using conda , python3.8. It seems DDS could start, but there is  error in the web ui when it is loading default dataset. Also, I can create an account with ddsop; but cannot login with the created account.

**Comment by AllenDun** [comment]
I found DDS did support Ubuntu20.04, there are errors for version dds 0.12.1, it is OK for lower version, dds 0.11.1

**Comment by AllenDun** [comment]
install the dds with pip in conda env

**Comment by xifanii** [comment]
Hi, @AllenDun  thanks for your feedback.

**Comment by xifanii** [comment]
Hi, @AllenDun thanks for your feedback.
Regarding "there is error in the web UI when it is loading the default dataset" I would like to know the following questions for analysis:
1、Whether the web UI service has failed to start or if there are specific page errors. If it is a service startup failure, I would appreciate more detailed console error logs.
2、If there are specific page errors, please provide the page URL and a screenshot of the error page.
3、If there are toast notifications on specific pages indicating request errors, I would also appreciate it if you could use Chrome's DevTools 'network' tab to provide information about the interface errors or screenshots.

**Comment by AllenDun** [comment]
<img width="1116" alt="dds" src="https://github.com/IDEA-Research/deepdataspace/assets/14049868/480c3c0d-91e8-44e4-9906-b5b8dae4ba7c">
[nohup.txt](https://github.com/IDEA-Research/deepdataspace/files/15009777/nohup.txt)
The above is the log and screenshot.

for lower version, e.g. 0.11.1, it is all ok

**Comment by xifanii** [comment]
<img width="919" alt="image" src="https://github.com/IDEA-Research/deepdataspace/assets/9626111/d0f74108-b7df-49ef-9ecf-34313725da32">

**Comment by xifanii** [comment]
@AllenDun thanks for your response.
Based on the log files you provided, I noticed that the JS files loaded on your page correspond to version v0.12.0. 
If you are actually using version v0.12.1, this issue may be caused by the HTML's browser cache leading to the wrong version of JS being loaded. You might try forcibly clearing your browser's cache to resolve the issue. 
If the problem still persists, I would recommend taking a screenshot of the overall network request status in Chrome's DevTools under the Network tab, to help us further diagnose the issue.
<img width="881" alt="image" src="https://github.com/IDEA-Research/deepdataspace/assets/9626111/19673e72-09ca-4c83-950a-85cc7c3cd902">

**Comment by AllenDun** [comment]
@xifanii, hi, after clear the chrome cache, problem still there, reproduce the issue steps: 
1. os ubuntu20.04, conda, docker container
2. conda create -n dds python=3.8
3. pip install deepdataspace
4. dds --host xxxx --port 8675 --quickstart -V
<img width="1116" alt="chrome-screenshot" src="https://github.com/IDEA-Research/deepdataspace/assets/14049868/1289db5d-3afc-4060-9566-4a27a16ac748">

**Comment by xifanii** [comment]
@AllenDun Thank you very much for your help. 
We have identified that the issue was caused by incorrect configuration of the backend API path in the web interface. 
This has been fixed and the version has been updated.
https://github.com/IDEA-Research/deepdataspace/releases/tag/v0.12.2

Please reinstall the latest version to resolve the issue.
